---
title: "Katelyn Gostic - CFA: A new center at the US CDC focused on building response-ready modeling tools"
date: 2023-06-07
comments: false
---


On Wednesday the 7th of June at 2pm UK time Katelyn Gostic will be introducing the new US CDC [Centre for Forecasting and Outbreak Analytics (CFA)](https://www.cdc.gov/forecast-outbreak-analytics/index.html). *More details to follow*

Katelyn is the nowcasting and natural history team lead within the real-time analysis branch of the Predict arm of the new CFA centre. Prio to this McDonnell Foundation Complex Systems Postdoc after completing her PhD at UCLA. As a doctoral student, she studied immune imprinting, a pattern in which individuals retain particularly strong, lifelong immune memory of the influenza viruses encountered in childhood, sometimes at the expense of equally strong protection against strains encountered later in life.

Now Katie studies the immune processes that allow such biases in immune memory to develop. Ultimately, her research aims to understand epidemiological outcomes as an emergent property of within-host immu Postdoc after completing her PhD at UCLA. As a doctoral student, she studied immune imprinting, a pattern in which individuals retain particularly strong, lifelong immune memory of the influenza viruses encountered in childhood, sometimes at the expense of equally strong protection against strains encountered later in life.

Now Katie studies the immune processes that allow such biases in immune memory to develop. Ultimately, her research aims to understand epidemiological outcomes as an emergent property of within-host immu


Kelly is a Prevention Effectiveness Fellow at the US CDC. Prior to this they conducted a PhD focussed on the 2014-2017 Zika and Chikungunya epidemics in Columbia using spatial interaction models to explore the spatial and temporal invasion dynamics of epidemics. Read more of Kelly's work [here](https://scholar.google.com/citations?user=OKbTKFUAAAAJ).

A recording of this talk will be posted to [our community site](https://community.epinowcast.org/c/meetings/8) a week after it is scheduled to take place. You can also ask questions ahead of time and asynchronously there.

## Connect to seminars

You can sign up for our event calendar here: [Google calendar ](https://calendar.google.com/calendar/u/0/r?cid=YTExM2I2ZjVkOTYxODA4ZjA5YjdhODA3ZTIwMzU1Mzk4ODY0Y2NhYjIzOWVkNjAyYzc5ZTkzYWM5OWY0YWQxM0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Or here for non-Google calendar users: [ICAL link ](https://calendar.google.com/calendar/ical/a113b6f5d961808f09b7a807e20355398864ccab239ed602c79e93ac99f4ad13%40group.calendar.google.com/public/basic.ics)

Or just join seminars directly here: [https://lshtm.zoom.us/j/8290218109 ](https://lshtm.zoom.us/j/8290218109)

More details about this seminar series are available [here](../seminars.qmd).