---
title: "Rebecca Borchering - Informing short term forecasts of categorical trends in confirmed influenza hospital admissions in the US using real-time effective reproduction number estimates"
date: 2023-12-06
comments: false
---

On Wednesday the 6th of December at 3pm UK time Rebecca Borchering will be talking about "Informing short term forecasts of categorical trends in confirmed influenza hospital admissions in the US using real-time effective reproduction number estimates". 

Rebecca Borchering is a Mathematical Statistician leading influenza modeling and forecasting efforts, such as the FluSight influenza forecasting collaboration, in the Applied Research and Modeling Team in the Influenza Division of the US Centers for Disease Control. They were a founding member of the COVID-19 Scenario Modeling Hub and have experience modeling infectious disease dynamics in multiple pathogen systems. Rebecca was also part of a team that recently published a [CDC technical blog on improving the CDC's tool for assessing epidemic growth](https://www.cdc.gov/forecast-outbreak-analytics/about/technical-blog-rt.html). For more on their work see [here](https://scholar.google.com/citations?user=JvBiQQYAAAAJ&hl=en) for their published research.

A recording of this talk will be posted to our [YouTube channel](https://www.youtube.com/channel/UC9qvwwGTudtKnOE-sM1LooQ) and asynchronous discussion will be possible on [our community site](https://community.epinowcast.org/c/meetings/8). You can also ask questions ahead of time and asynchronously there.

## Connect to seminars

You can sign up for our event calendar here: [Google calendar ](https://calendar.google.com/calendar/u/0/r?cid=YTExM2I2ZjVkOTYxODA4ZjA5YjdhODA3ZTIwMzU1Mzk4ODY0Y2NhYjIzOWVkNjAyYzc5ZTkzYWM5OWY0YWQxM0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Or here for non-Google calendar users: [ICAL link ](https://calendar.google.com/calendar/ical/a113b6f5d961808f09b7a807e20355398864ccab239ed602c79e93ac99f4ad13%40group.calendar.google.com/public/basic.ics)

Or just join seminars directly here: [https://lshtm.zoom.us/j/8290218109 ](https://lshtm.zoom.us/j/8290218109)

To get an email with details of community meetings you can sign up to our community forum and watch (using the bell on the top right) the [Meeting category](https://community.epinowcast.org/c/meetings/8).

More details about this seminar series are available [here](../../seminars.qmd).