---
title: "Tomás León - CalCAT: Past, Present, and Future for California's Use of Infectious Disease Modeling in Public Health Response"
date: 2024-03-06
comments: false
---

On Wednesday the 6th of March at 3pm UK time, Tomás León will be talking about California's use of infectious disease modeling in public health response.

In this talk, Tomás will discuss CalCAT, a public-facing modeling hub for California and its counties, which was launched with partners in 2020 as part of the COVID-19 response. He will also talk about the Modeling and Advanced Analytics Team, which was founded during the pandemic to synthesize modeling results being generated and produce internal modeling products to support the state's public health response activities.

Tomás León is the Modeling Section Chief at the California Department of Public Health (CDPH). Before joining CDPH as part of the COVID-19 response in 2020, he was a researcher at the University of California, Berkeley, who focused on macroparasite modeling and modeling related to the ecology of mosquito-borne diseases. His current focus is on expanding the use of infectious disease modeling tools at CDPH for public health decision making and integrating best modeling practices in collaboration with external partners. For more on his work see [here](https://tomasleon.com/). 

A recording of this talk will be posted to our [YouTube channel](https://www.youtube.com/channel/UC9qvwwGTudtKnOE-sM1LooQ) and asynchronous discussion will be possible on [our community site](https://community.epinowcast.org/c/meetings/8). You can also ask questions ahead of time and asynchronously there.

## Connect to seminars

You can sign up for our event calendar here: [Google calendar ](https://calendar.google.com/calendar/u/0/r?cid=YTExM2I2ZjVkOTYxODA4ZjA5YjdhODA3ZTIwMzU1Mzk4ODY0Y2NhYjIzOWVkNjAyYzc5ZTkzYWM5OWY0YWQxM0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

Or here for non-Google calendar users: [ICAL link ](https://calendar.google.com/calendar/ical/a113b6f5d961808f09b7a807e20355398864ccab239ed602c79e93ac99f4ad13%40group.calendar.google.com/public/basic.ics)

Or just join seminars directly here: [https://lshtm.zoom.us/j/8290218109 ](https://lshtm.zoom.us/j/8290218109)

To get an email with details of community meetings you can sign up to our community forum and watch (using the bell on the top right) the [Meeting category](https://community.epinowcast.org/c/meetings/8).

More details about this seminar series are available [here](../../seminars.qmd).
